name: Run tests for Node.js app in CI

on: [push, pull_request]

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    container:
      image: node:12
      env:
        NODE_ENV: test

    steps:
    - uses: actions/checkout@v2

    - run: yarn install

    - name: Run test suite
      run: yarn test
